source 'http://rubygems.org'

gem 'rake'
gem 'html-proofer'
gem 'sanitize'

group :jekyll_plugins do
  gem 'jekyll'
  gem 'jekyll-admin'
  gem 'jekyll-paginate'
  gem 'support-for'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jekyll-livereload'
end
