source 'http://rubygems.org'

gem 'rake'
gem 'sanitize'

group :development, :test do
  gem 'pry'
  gem 'html-proofer'
end

group :jekyll_plugins do
  gem 'jekyll'
  gem 'jekyll-admin'
  gem 'jekyll-paginate'
  gem 'support-for'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jekyll-livereload'
end
