task default: 'test'

namespace :upsert_data_by_readme do
  desc 'Upsert company data from English README'
  task :en do
    ruby "upsert_data_by_readme.rb en"
  end

  desc 'Upsert company data from Japanese README'
  task :ja do
    ruby "upsert_data_by_readme.rb ja"
  end

  desc 'Upsert company data for both languages'
  task :all do
    ruby "upsert_data_by_readme.rb en"
    ruby "upsert_data_by_readme.rb ja"
  end
end

require 'html-proofer'
# cf. GitHub - gjtorikian/html-proofer
# https://github.com/gjtorikian/html-proofer

task test: [:build] do
  options = {
    allow_hash_href:  true,
    assume_extension: true,
    check_opengraph:  true,
    check_favicon:    true,
    check_html:       true,
    disable_external: true,

    # NOTE: You can ignore file, URL, and response as follows
    file_ignore: [
      './_site/google3a4de0d83c05ed13.html',
    ],
    #url_ignore:  %w(example.com),
    #http_status_ignore: [0, 500, 999],
  }

  HTMLProofer.check_directory('./_site', options).run
end

# Enable 'build' to flush cache files via 'clean'
task build: [:clean] do
  system 'bundle exec jekyll build'
end

task :clean do
  system 'bundle exec jekyll clean'
end
